### ISSUE TITLE
Save Editor Prototype

### ISSUE THREAD

**Issue by neptuwunium** [Xeeynamo/ffxv#3]
I assume you never got around to finishing the save editor prototype, but would you be willing to update this repository with any code you do still have? 

Forspoken uses much of the same format as XV, and like XV it also uses the same encryption scheme so I was hoping someone else already reverse engineered that part in particular.

As far as I can tell is that it gathers a xorshift seed from the save file and performs an absurd number of xorshift rounds on it followed by random number iterations to tweak the main AES IV.

**Comment by Xeeynamo** [comment]
Hey @yretenai , all the code was already pushed on GitHub. Unfortunately I lost interest in FFXV years ago and it is unlikely I will resume any work related to it.

I am closing the issue, but be free to ask any other question you have here.
