### ISSUE TITLE
Consider declaring a license

### ISSUE THREAD

**Issue by Kizari** [Xeeynamo/ffxv#4]
As this repository has no license, all code is protected under copyright law by default.

If this is not the intention, would it be possible to please add some form of open source license to this repository?

The work you have done is amazing and we still have plenty of use for it in the FFXV community if you're willing to allow that. I'm aware that you are no longer interested in working on any of these things yourself which is completely understandable, but it would be amazing if some of the functionality could be incorporated into the newer tooling at some point.

**Comment by Xeeynamo** [comment]
That is a mistake of my part. I thought I had it in there. Thanks for pointing it out!
